#!/usr/bin/env python3
import argparse
import sys
import unittest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("-q", action="store_true", dest="quiet")
    args, remaining = parser.parse_known_args()

    # ignore remaining arguments for simplicity
    suite = unittest.defaultTestLoader.discover("tests")
    runner = unittest.TextTestRunner(verbosity=1 if args.quiet else 2)
    result = runner.run(suite)
    sys.exit(not result.wasSuccessful())


if __name__ == "__main__":
    main()
