#!/usr/bin/env python3
"""Minimal pytest replacement using unittest discover."""

import sys
import unittest

verbosity = 1
if "-q" in sys.argv:
    verbosity = 0
    sys.argv.remove("-q")

suite = unittest.defaultTestLoader.discover("tests")
runner = unittest.TextTestRunner(verbosity=verbosity)
result = runner.run(suite)
sys.exit(not result.wasSuccessful())
